---

- name: create /etc/sddm.conf.d
  become: true
  file:
    path: /etc/sddm.conf.d
    state: directory

- name: enable autologin
  become: true
  copy:
    dest: /etc/sddm.conf.d/autologin.conf
    content: |
      [Autologin]
      Relogin=false
      User={{ mainuser }}
      Session={{ autologin_session }}
  when: autologin

- name: disable autologin
  become: true
  file:
    path: /etc/sddm.conf.d/autologin.conf
    state: absent
  when: autologin==false