---
packages:
  # required to boot
  - linux
  - base
  - base-devel
  # Virtual devices
  - cryptsetup
  - btrfs-progs
  # Miscilaniues
  - sudo
  - python3
  - man
  - tldr
  - usbutils # lsusb
  - zsh
  # network
  - dhcpcd
  - openssh
  # show system information
  - neofetch
  - bashtop

dev_packages:
  # ARM
  - arm-none-eabi-binutils
  - arm_none-eabi-gcc
  - arm-none-eabi-newlib
  # C
  - cmake
  - gcc
  - clang
  # virtualisation
  - docker
  - docker-compose
  - ansible
  # other
  - ffmpeg
  - node
  - zig
  - rust
  - ocaml
  - ghc
  - go
  

wireless_packages:
  - networkmanager
  - wpa_supplicant
