---
- name: copy 
  become: yes
  ansible.builtin.copy:
      src: files/etc/
      dest: /etc/
      owner: root
      group: root
      mode: 'preserve'
      decrypt: true

- name: copy logind.conf
  become: yes
  ansible.builtin.copy:
      src: files/logind.conf
      dest: /etc/systemd/logind.conf
      owner: root
      group: root
      mode: 'preserve'
      decrypt: true
  when: laptop
