---
- name: install basic packages
  become: true
  pacman:
    name: "{{ packages }}"
    state: present

- name: Check if running in a virtual machine
  set_fact:
    is_virtual: "{{ ansible_virtualization_type is defined and ansible_virtualization_type != 'physical' }}"

- name: Install linux-firmware if not running in a virtual machine
  become: true
  pacman:
    name: linux-firmware
    state: present
  when: not is_virtual

- name: Start services if available
  become: true
  service:
    name: "{{ item }}"
    state: started
    enabled: true 
  ignore_errors: true
  loop:
    - sshd
    - dhcpcd
    - NetworkManager


#sudo hostnamectl set-hostname mainpc